apiVersion: apps/v1
kind: Deployment
metadata:
  name: webby-deploy
  labels:
    app: webby
spec:
  selector:
    matchLabels:
      app: webby
  replicas: 3
  template:
    metadata:
      labels:
        app: webby
    spec:
      containers:
      - name: webby-deploy
        image: reg.alta3.com/5219-brockel-webby
        ports:
        - containerPort: 8888
